### ISSUE TITLE
`$currentLocale` store replicating functionality from existing `typesafe-i18n` locale store

### ISSUE THREAD

**Issue by ivanhofer** [munkacsimark/typing-app#1]
Hi,
I'm happy to see that you are using `typesafe-i18n` in your project :)
I took a quick look around your repo and saw that you mentioned that `$locale` is not working.
I just cloned your repo and tried to run it with `$locale` as a replacement of your `currentLocale`-store and it was working for me.

Can you please explain what error message you get?

**Comment by munkacsimark** [comment]
Hi @ivanhofer! Really thanks for looking into it! There is no error message. What is happening, I'm trying to get the current locale like `$locale` after `initI18n('en')` and I'm getting an empty string. I'm expecting `$locale` to be `'en'`, Am I doing something wrong? 🙃

**Comment by ivanhofer** [comment]
I have created a PR #2 that gets rid of $currentLocale and should work the same as before.

**Comment by munkacsimark** [comment]
@ivanhofer, now I'm seeing what was the issue. Thanks again for helping with this! 🙏
